[project]
name = "agent"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pyaudio>=0.2.14",
    "pydantic>=2.11.7",
    "pydantic-ai>=0.4.2",
    "python-dotenv>=1.1.1",
    "speechrecognition>=3.14.3",
    "tzlocal>=5.3.1",
]
